-- ==========================================================
-- Project      : Amazon Ecommerce Analytics
-- Phase        : Aggregate Functions
-- Author       : Neha Yadav
-- Tool         : PostgreSQL
-- Database     : Amazon_Sales_Analytics_DB
-- Total Queries: 15
-- ==========================================================

-- ==========================================================
-- Query 1 : Count total orders
-- Purpose : Find total number of orders
-- SQL Concept Used : COUNT()
-- ==========================================================

SELECT COUNT(*) AS total_orders
FROM amazon_sales;

-- ==========================================================
-- Query 2 : Calculate total sales
-- Purpose : Find total revenue
-- SQL Concept Used : SUM()
-- ==========================================================

SELECT SUM(amount) AS total_sales
FROM amazon_sales;

-- ==========================================================
-- Query 3 : Calculate average order value
-- Purpose : Find average sales amount
-- SQL Concept Used : AVG()
-- ==========================================================

SELECT ROUND(AVG(amount),2) AS average_order_value
FROM amazon_sales;

-- ==========================================================
-- Query 4 : Highest order amount
-- Purpose : Find maximum order value
-- SQL Concept Used : MAX()
-- ==========================================================

SELECT MAX(amount) AS highest_order_amount
FROM amazon_sales;

-- ==========================================================
-- Query 5 : Lowest order amount
-- Purpose : Find minimum order value
-- SQL Concept Used : MIN()
-- ==========================================================

SELECT MIN(amount) AS lowest_order_amount
FROM amazon_sales;

-- ==========================================================
-- Query 6 : Total quantity sold
-- Purpose : Calculate total quantity of products sold
-- SQL Concept Used : SUM()
-- ==========================================================

SELECT SUM(qty) AS total_quantity_sold
FROM amazon_sales;

-- ==========================================================
-- Query 7 : Count cancelled orders
-- Purpose : Find total cancelled orders
-- SQL Concept Used : COUNT()
-- ==========================================================

SELECT COUNT(*) AS cancelled_orders
FROM amazon_sales
WHERE status = 'Cancelled';

-- ==========================================================
-- Query 8 : Count shipped orders
-- Purpose : Find total shipped orders
-- SQL Concept Used : COUNT()
-- ==========================================================

SELECT COUNT(*) AS shipped_orders
FROM amazon_sales
WHERE status = 'Shipped';

-- ==========================================================
-- Query 9 : Average quantity per order
-- Purpose : Calculate average quantity purchased
-- SQL Concept Used : AVG()
-- ==========================================================

SELECT ROUND(AVG(qty),2) AS average_quantity
FROM amazon_sales;

-- ==========================================================
-- Query 10 : Highest quantity purchased
-- Purpose : Find maximum quantity in a single order
-- SQL Concept Used : MAX()
-- ==========================================================

SELECT MAX(qty) AS highest_quantity
FROM amazon_sales;

-- ==========================================================
-- Query 11 : Lowest quantity purchased
-- Purpose : Find minimum quantity in a single order
-- SQL Concept Used : MIN()
-- ==========================================================

SELECT MIN(qty) AS lowest_quantity
FROM amazon_sales;

-- ==========================================================
-- Query 12 : Count orders having amount
-- Purpose : Count records where amount is available
-- SQL Concept Used : COUNT(column)
-- ==========================================================

SELECT COUNT(amount) AS orders_with_amount
FROM amazon_sales;

-- ==========================================================
-- Query 13 : Count orders with missing amount
-- Purpose : Identify missing amount records
-- SQL Concept Used : COUNT() + WHERE
-- ==========================================================

SELECT COUNT(*) AS missing_amount_orders
FROM amazon_sales
WHERE amount IS NULL;

-- ==========================================================
-- Query 14 : Average sales of shipped orders
-- Purpose : Calculate average order value for shipped orders
-- SQL Concept Used : AVG() + WHERE
-- ==========================================================

SELECT ROUND(AVG(amount),2) AS average_shipped_sales
FROM amazon_sales
WHERE status = 'Shipped';

-- ==========================================================
-- Query 15 : Total revenue from shipped orders
-- Purpose : Calculate total revenue generated by shipped orders
-- SQL Concept Used : SUM() + WHERE
-- ==========================================================

SELECT SUM(amount) AS shipped_revenue
FROM amazon_sales
WHERE status = 'Shipped';


-- ==========================================================
-- Concepts Covered
--
-- COUNT()
-- COUNT(column)
-- SUM()
-- AVG()
-- MIN()
-- MAX()
-- ROUND()
-- Aggregate Functions with WHERE
--
-- Total Queries : 15
-- Phase Status  : Completed Successfully
--
-- End of File
-- ==========================================================

